#!/usr/bin/python

import os
import sys

sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))

from charmhelpers.core import (
    hookenv,
    host,
    fetch,
)

hooks = hookenv.Hooks()
log = hookenv.log

SERVICE = 'postfix'


@hooks.hook('install')
def install():
    log('Installing postfix')
    fetch.apt_install(fetch.filter_installed_packages(['postfix']))


if __name__ == "__main__":
    # execute a hook based on the name the program is called by
    hooks.execute(sys.argv)
